# Generated by Django 6.0.4 on 2026-05-08 16:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='api_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_base_url', models.CharField(max_length=250, unique=True)),
                ('api_username', models.CharField(default='', max_length=250)),
                ('_api_password', models.CharField(blank=True, db_column='api_password', max_length=250, null=True)),
                ('_api_key', models.CharField(blank=True, db_column='api_key', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='database_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('database_type', models.CharField(choices=[('postgres', 'postgres'), ('sqlite', 'sqlite'), ('other', 'other')], max_length=25)),
                ('database_url', models.CharField(max_length=250)),
                ('database_port', models.CharField(default='5432', max_length=250)),
                ('database_name', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='datatable_groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatable_group', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('staff', 'staff'), ('stakeholder', 'stakeholder'), ('other', 'other')], default='other', max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='database_user_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_username', models.CharField(max_length=250)),
                ('_db_password', models.CharField(db_column='db_password', max_length=250)),
                ('connection_to_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.database_connection')),
                ('user_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='datatable_connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatable_name', models.CharField(max_length=250)),
                ('databale_type', models.CharField(choices=[('data', 'data'), ('mapping', 'mapping'), ('other', 'other')], default='data', max_length=25)),
                ('user_db_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.database_user_connection')),
            ],
        ),
        migrations.CreateModel(
            name='connection_functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_function_name', models.CharField(max_length=50)),
                ('function_type', models.CharField(choices=[('data', 'data'), ('mapping', 'mapping'), ('action', 'action'), ('other', 'other')], default='data', max_length=25)),
                ('function_extension', models.CharField(max_length=250)),
                ('function_input_values_schema', models.CharField(max_length=2500)),
                ('function_output_type', models.CharField(blank=True, default='', max_length=250)),
                ('function_output_extensions', models.CharField(blank=True, default='', max_length=250)),
                ('connection_to_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.api_connection')),
                ('connection_to_datable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.datatable_connection')),
            ],
        ),
        migrations.CreateModel(
            name='datatable_dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('numeric', 'numeric'), ('date', 'date'), ('string', 'string'), ('other', 'other')], max_length=25)),
                ('dictionary_table_key', models.CharField(default='', max_length=250)),
                ('data_value_column', models.CharField(max_length=250)),
                ('data_connection_function', models.ForeignKey(limit_choices_to={'function_type': 'data'}, on_delete=django.db.models.deletion.CASCADE, to='synapse.connection_functions')),
            ],
        ),
        migrations.CreateModel(
            name='connection_function_saved_inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_value', models.CharField(max_length=2500)),
                ('input_value_name', models.CharField(max_length=250)),
                ('input_value_description', models.CharField(default='', max_length=500)),
                ('input_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.datatable_dictionary')),
                ('user_connection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='dictionary_keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(max_length=250, unique=True)),
                ('unique_key_desc', models.CharField(max_length=2500, unique=True)),
                ('datatable_group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.datatable_groups')),
            ],
        ),
        migrations.AddField(
            model_name='datatable_dictionary',
            name='dictionary_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.dictionary_keys'),
        ),
        migrations.CreateModel(
            name='local_function_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_function_type', models.CharField(choices=[('xlsx', 'xlsx'), ('python', 'python'), ('other', 'other')], max_length=25)),
                ('local_function_path', models.CharField(max_length=250)),
                ('local_function_name', models.CharField(max_length=250)),
                ('function_input_values_schema', models.CharField(default='', max_length=2500)),
                ('user_connection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='local_data_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_file_type', models.CharField(choices=[('xlsx', 'xlsx'), ('csv', 'csv'), ('other', 'other')], max_length=25)),
                ('local_file_path', models.CharField(max_length=250)),
                ('local_file_path_old', models.CharField(default='', max_length=250)),
                ('local_file_name', models.CharField(default='', max_length=250)),
                ('local_file_sheet', models.CharField(default='', max_length=250)),
                ('local_file_header', models.CharField(default='0', max_length=250)),
                ('user_connection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='input_value_to_connections_function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_connection_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.connection_functions')),
                ('input_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.connection_function_saved_inputs')),
                ('user_connection', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info')),
            ],
        ),
        migrations.AddField(
            model_name='api_connection',
            name='user_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synapse.user_info'),
        ),
        migrations.AddConstraint(
            model_name='connection_functions',
            constraint=models.CheckConstraint(condition=models.Q(('connection_to_datable', None), ('connection_to_api', None), _connector='OR'), name='at_least_1_non_null_con'),
        ),
        migrations.AddConstraint(
            model_name='connection_functions',
            constraint=models.CheckConstraint(condition=models.Q(('connection_to_datable', None), ('connection_to_api', None), _connector='OR'), name='at_least_1_null_con'),
        ),
        migrations.AddConstraint(
            model_name='api_connection',
            constraint=models.CheckConstraint(condition=models.Q(('_api_password', None), ('_api_key', None), _connector='OR'), name='at_least_1_non_null_api'),
        ),
        migrations.AddConstraint(
            model_name='api_connection',
            constraint=models.CheckConstraint(condition=models.Q(('_api_password', None), ('_api_key', None), _connector='OR'), name='at_least_1_null_api'),
        ),
    ]
