# Generated by Django 6.0.4 on 2026-05-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api_connection',
            name='api_headers',
            field=models.TextField(default=''),
        ),
    ]
