# Generated by Django 6.0.4 on 2026-05-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0002_api_connection_api_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_data_files',
            name='local_file_header',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='local_data_files',
            name='local_file_path_old',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='local_data_files',
            name='local_file_sheet',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
