# Generated by Django 6.0.4 on 2026-05-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0003_alter_local_data_files_local_file_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable_dictionary',
            name='dictionary_table_key',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
