# Generated by Django 6.0.4 on 2026-05-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synapse', '0004_alter_datatable_dictionary_dictionary_table_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_function_saved_inputs',
            name='input_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='synapse.dictionary_keys'),
        ),
    ]
